.github/workflows/deploy.yml

Forgot to add the `environment` expression to activate the correct environment:
* `main`
* `test`
* `prod`
These correspond to the repo environments: https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/settings/environments
Each environment holds the specific deploy secrets and variables.

Fix: deploy workflow environments

---

.gitignore
web/core/templates/core/base.html
web/settings.py

- Serve static files from `/static` virtual path (already mapped in `nginx`)
- Configure static files storage to use [ManifestStaticFileStorage](https://docs.djangoproject.com/en/5.1/ref/contrib/staticfiles/#manifeststaticfilesstorage)
- Maintain static files in `web/static/` e.g. `web/static/css/` for CSS files, or `web/static/img/` for static image files
- Placeholder site CSS file at `web/static/css/styles.css` included in `base.html` template

Feat: static files config

---

appcontainer/Dockerfile
bin/reset_db.sh
bin/start.sh
web/settings.py

`bin/start.sh` calls `bin/reset_db.sh` instead of the other way around, so that the devcontainer doesn't break when it starts and calls `bin/reset_db.sh`!
Also relax environment check for `dev`/`test` which is currently failing.

Fix: startup and runtime

---

tests/pytest/conftest.py
tests/pytest/vital_records/test_views.py
web/vital_records/urls.py
web/vital_records/views.py

Closes #45 
Adds tests for each view class as well.
`web.vital_records` was the only app that had view functions defined.
`web.core` doesn't define view functions and already used built-in class-based views: https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/blob/main/web/core/urls.py

Refactor: use class-based views in `vital_records`

---

tests/pytest/vital_records/test_views.py
web/vital_records/urls.py
web/vital_records/views.py

Initializing session as if user had come in through `IndexView`.
Closes #42 
~On top of #48~ 
1. Check out this branch in the devcontainer
2. Reset your database if needed `bin/reset_db.sh` (you need a valid `vital-records` flow and IdG connection details)
3. Launch the app with `F5`
4. Go to the URL `http://localhost:44370/vital-records/login`
5. Redirect to the Login.gov sandbox, sign in with a disaster-affected sandbox account
6. Redirect back to DDRC, see the expected [`RequestView`](https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/blob/main/web/vital_records/views.py#L17)

Feat: `vital_records` view redirects to OAuth flow

---

terraform/azure-pipelines.yml

We don't need individual `dev` and `prod` jobs since we only have a single service connection, and the existing code selects the Terraform workspace correctly.

Chore: combine Azure pipeline jobs

---

web/core/templates/core/base.html

closes #65 
Segacy recently updated the footer to be more simple - removing the tall top portion of it. This PR achieves that layout for all pages. This PR also removes the web accessibility certification link, as it is not in the Figma designs.

Footer: Simplify footer

---

terraform/container_app.tf
terraform/environment.tf
terraform/pipeline/deploy.yml
terraform/pipeline/tags.py
terraform/variables.tf

Closes #67
Defines a new [Container App](https://learn.microsoft.com/en-us/azure/container-apps/overview) resource via Terraform for the main web app. 
The `image:tag` to comes from variables that are derived from branch/tag metadata during the deploy pipeline run.
This does not yet replace the existing `azurerm_linux_web_app` definition or deployment (e.g. for the existing POC site).

Feat: use Azure Container App

---

terraform/container_app.tf
terraform/pipeline/deploy.yml
terraform/pipeline/tags.py

Follow up to #64 
The most recent [`terraform apply`](https://calenterprise.visualstudio.com/CDT.ODS.DDRC/_build/results?buildId=78831&view=logs&j=e2b2897c-f736-5615-5c9c-c20ddcd4aa73&t=ce99383a-5c73-5e0e-b029-4934b8ac07e5) timed out after about 20 minutes of trying to deploy the container app.
When I created this through the UI, I didn't use a readiness probe or anything else, so removing that here.
Also fixing the deploy pipeline to always send the commit SHA as an input variable to `plan/apply`, rather than sometimes using `main`. This could cause problems for our `dev` environment where it doesn't actually get redeployed / a new instance.

Fix: Container app pipeline deployment

---

terraform/.gitignore
terraform/container_app.tf
terraform/init.sh
terraform/key_vault.tf

- enable `SystemAssigned` Identity
- policy for access to Key Vault for secrets
- small cleanups to normalize  with existing state
Part of https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/issues/46

Fix: Terraform container app definition

---

.github/workflows/deploy.yml

Part of #46.
@thekaveman created the PAT in Azure DevOps, and added it as a repository secret here. 
* The PAT expires on: `2025-06-30`
* The PAT has the following scopes: `Build (Read & execute)`
This is a temporary solution until the more permanent Service Principal based approach can be implemented.

CI: login to ADO with PAT

---

web/core/templates/core/base.html
web/static/css/styles.css
web/vital_records/templates/vital_records/base.html
web/vital_records/templates/vital_records/index.html
web/vital_records/templates/vital_records/request.html
web/vital_records/templates/vital_records/submitted.html
web/vital_records/templates/vital_records/unverified.html

closes #53 
- Removes some unnecessary header elements, as per Figma
- Removes CSS for those unnecessary header elements
- Adds the headline section with breadcrumb link. (Link location to be updated when link is available).
- The header section is taken from here: https://office-of-digital-services.github.io/California-State-Web-Template-HTML/top-task-1/index.html in the template docs
- Changed the way the `<main>` landmark was wrapping, to ensure a11y rule: all content contained in landmarks

Base template for form pages

---

terraform/container_app.tf
web/settings.py

Part of #68 
In Azure, the Postgres server is running in a container app inside the same container app environment as the web container app (Django).
The Postgres container doesn't allow ingress from the public Internet, only from within the container app environment, and all traffic stays within Azure (i.e. doesn't travel over the public Internet).
The Postgres container is also not setup for SSL connections right now.

Fix: sslmode=disable for Azure connection

---

terraform/container_app.tf
terraform/storage.tf

Unlike the [original file share that was removed](https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/pull/88#issue-3015196543), this one is different in a few ways:
* SMB protocol
* Read-only
It works for mounting in simple static files like fixtures etc.

Feat: fileshare for web container app

---

web/static/css/styles.css
web/vital_records/templates/vital_records/_form_progress.html

closes #54 
- Does not show up on mobile
- The steps are not clickable
- Created a class, called `sm` (as in `small`). Adding this `sm` style to the existing `cagov-step-list` will turn the default list to look like this smaller, more compact list.
- I did NOT add any new CSS variables for colors. This element uses a blue `#005ea2` and a light gray `#e6e6e6`. Both Bootstrap and the CA State Web Template and the color schemes have many blues and grays, so perhaps, after the deadline, we can use an existing blue and gray instead of adding more of our own? Color options: https://template.webstandards.ca.gov/visual-design/color.html
- Not using `rems` yet. I haven't been able to figure out the exact reason.. but during development, I've been seeing 1rem=14px on some pages and 16px on others.

Styles: Style the form progress sidebar

---

web/static/css/styles.css
web/vital_records/templates/vital_records/_two_column_form.html
web/vital_records/templates/vital_records/base.html
web/vital_records/templates/vital_records/request/county.html
web/vital_records/templates/vital_records/request/dob.html
web/vital_records/templates/vital_records/request/eligibility.html
web/vital_records/templates/vital_records/request/order.html
web/vital_records/templates/vital_records/request/statement.html
web/vital_records/templatetags/form_helpers.py

closes #106 
- Creates a new `label_with_required` form helper tag
- Update all the form fields to use this `label_with_required` tag. The tag helper will determine if the field is required or not, and if it is, it will add HTML for the required title/asterisks. 
- https://designsystem.digital.gov/templates/form-templates/#identifying-required-fields-2
- https://www.w3.org/WAI/WCAG22/Techniques/html/H90

Form: Required labels

---

pyproject.toml

Chore: pin verison of `django-cdt-identity`

---

web/static/css/styles.css
web/vital_records/templates/vital_records/base.html
web/vital_records/templates/vital_records/request/county.html
web/vital_records/templates/vital_records/request/dob.html
web/vital_records/templates/vital_records/request/eligibility.html
web/vital_records/templates/vital_records/request/name.html
web/vital_records/templates/vital_records/request/order.html
web/vital_records/templates/vital_records/request/parents.html
web/vital_records/templates/vital_records/request/statement.html

#43, requires the required label PR be merged first
- Style the header section
- Style the form fields, select fields, labels
- Style the typography
- Style form spacing
- Fixes some spacing so the form looks good in mobile
- Tried to use as much Bootstrap and CA State Web Template when possible. Wrote custom CSS scoped under #vital-records for the rest.

Form styling

---

terraform/web.tf
terraform/worker.tf
web/core/urls.py

Both container apps (`web` and `worker`) read and/or write to each DB, so they both need credentials for each.

Fix: terraform environment vars

---

bin/worker.sh
terraform/key_vault.tf
terraform/worker.tf

Running the worker once per minute is very slow, allowing only a max of 30 requests processed per hour (since there are 2 tasks per request).
Instead keep the worker running continuously to process tasks as they hit the queue.

Refactor: convert worker to long-running container app

---

web/static/css/styles.css
web/vital_records/templates/vital_records/base.html

Go to vital records home now goes to: https://www.test-cagov.cdt.ca.gov/lafires/vital-records/
Added CSS to ensure the external link icon doesn't show up.

Fix: Add correct demo link

---

web/vital_records/tasks.py

The value in the PDF select box is `WILDFIRE_CDPH_VR_B0A6353F1` although the display value is `WILDFIRE`

Fix: update formtype field value in package

---

tests/pytest/core/management/commands/test_ensure_db.py
web/core/management/commands/ensure_db.py

The call to `self.style.ERROR(e)` was treating `e` as a str and trying to call a str method, causing another exception that masked the true exception `e`.
Part of #150

Fix: log statement in ensure_db

---

bin/setup.sh
tests/pytest/core/management/commands/test_ensure_db.py
web/core/management/commands/ensure_db.py

Previously, we ensured schema permissions _after the user was created_ but _before the database was created_. If the database didn't exist, there is no schema target for the user grants!
This PR fixes the order of operations, so:
1. User is created if needed
2. Database is created if needed
3. If database was created, ensure schema permissions
This PR also adds a flag to the `ensure_db` command: `--reset` to completely reset the database(s); e.g. dropping user and database before creation. This is mostly useful in a local development environment, e.g. we want to startup the devcontainer with a fresh DB.
Part of #150

Fix: reorder user, schema, database steps in `ensure_db`

---

tests/pytest/conftest.py
tests/pytest/vital_records/test_mixins.py
tests/pytest/vital_records/test_session.py
tests/pytest/vital_records/test_views.py
web/vital_records/mixins.py
web/vital_records/session.py
web/vital_records/views.py

Closes #112 
* When a new `VitalRecordsRequest` is first created, save its primary key in the user's session
* On subsequent update pages for the request, validate that the session PK == the request PK

Feat: track and validate request ID in session

---

tests/pytest/core/management/commands/test_ensure_db.py
web/core/management/commands/ensure_db.py

Another part of #150
Postgres 13+ supports `WITH (FORCE)` that attempts to close existing connections, which would otherwise prevent the database from being dropped.

Fix: drop database with force

---

tests/pytest/core/management/commands/test_ensure_db.py
web/core/management/commands/ensure_db.py

Part of #150.
The admin role does in fact need to granted the user role, in order to create a database on behalf of that user. This seems to be an issue with the admin user in Azure PostgreSQL not being a true "superuser" like in local/Docker PostgreSQL.
During reset, revoke the role so that we can drop the user (avoiding the issue identified in #197).

Fix: revert user-->admin role grant, but revoke on reset

---

.devcontainer/Dockerfile
.dockerignore
.github/workflows/deploy.yml
appcontainer/Dockerfile
pyproject.toml

* ignore unneeded files/directory in Docker context
* improve Docker layer caching be ordering some commands
* use Buildkit cache mount to cache pip installs
* use Buildkit cache mounts to cache apt installs
* in CI/CD, explicitly use the `main` branch ref cache, so all Docker builds (e.g. `main` and tags) can take advantage

Feat: improve Docker caching

---

web/settings.py

Resolving an error seen running in Azure:
```log
connection failed: connection to server at "x.x.x.x", port 5432 failed: 
root certificate file "/home/cdt/.local/lib/python3.12/site-packages/certs/azure_postgres_ca_bundle.pem" does not exist
```
The bundle path is relative and pointing to `/home/cdt/.local/lib/python3.12/site-packages/certs`
But the bundle lives in `/cdt/app/certs`

Fix: make cert path absolute

---

.github/workflows/deploy.yml
appcontainer/Dockerfile

The requirements output can be moved into the image build itself, saving time in CI/CD.

Refactor: remove duplicative pip install

---

web/vital_records/forms.py
web/vital_records/templates/vital_records/request/dob.html

closes #165 
Update date of birth's month field to follow USWDS's guidance: https://designsystem.digital.gov/patterns/create-a-user-profile/date-of-birth/#guidance-2 by changing the text field into a Select field with the month displayed as a numberal and the name. Add a `Select` placeholder blank option. Month is still required. Month is displayed as a name on the confirmation still.

Refactor: Change Date of Birth's month to a Select

---

appcontainer/nginx.conf
terraform/modules/app_gateway/main.tf

Follow up to #236 
Part of #187 and #188 
* The App Gateway needs to have its `backend_settings.host_name` attribute match the container app's FQDN, so it knows where to route the traffic
* Nginx needs to forward the `X-Forwarded-Proto` and `X-Forwarded-Host` headers from the App Gateway for the [`USE_X_FORWARDED_HOST`](https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-USE_X_FORWARDED_HOST) Django setting to work correctly

Fix: correct host forwarding

---

terraform/pipeline/deploy.yml

Ensure the agent's IP isn't removed mid-apply, causing subsequent steps in the apply to fail.

Fix: allow agent ip during plan/apply

---

terraform/modules.tf
terraform/pipeline/deploy.yml
terraform/terraform.tfvars.sample
terraform/variables.tf

We don't need to hardcode the giant list of defaults, it has no effect.
There was a small correction to add the CIDR prefix `/32` to the dynamic IP address added in the pipeline, as required by Key Vault.

Refactor: pipeline allowed IPs

---

terraform/modules/key_vault/monitoring.tf
terraform/modules/key_vault/network.tf

Avoids issue where '/' is missing from object ID

Chore: use normalized Key Vault name

---

web/settings.py

Closes #253
1. Checkout the branch locally, rebuild/reopen devcontainer
2. Run through a vital records flow
3. Run and debug the `Django: QCluster once` profile once, confirm a PDF is generated
4. Log in to the Admin and look at `Tasks > Queued tasks`, confirm an `email` task is present
5. Run and debug the `Django: QCluster once` profile again, confirm an email is sent (either as a file to the local `./inbox` or via Azure to the `VITAL_RECORDS_EMAIL_TO` inbox)

Fix: store task success by default

---

pyproject.toml
tests/pytest/test_monitoring.py
web/monitoring.py

We are using the newer `psycopg` (v3) package, not the older `psycopg2` that Azure automatically instruments.
This will prevent alerts for exceptions like:
```
Exception occurred when instrumenting: psycopg2
```

Fix: `psycopg` instrumentation

---

web/static/css/styles.css
web/vital_records/templates/vital_records/request/confirm.html
web/vital_records/templates/vital_records/request/statement.html

Closes #274 
On that second TODO item, I had to add an element to the page and get its styling in, so here are some screenshots:
<details><summary>Screenshots</summary>
---
(full page)
</details>

Chore: copy updates

---

web/vital_records/templates/vital_records/_vertical_tracker.html

closes #306 
requires #310 to be merged first
- Refactor vertical tracker of the step list to use the steps mixin from #310 
- This should make the vertical tracker also ready for Marriage and Death flows. 
TIL: Django's `for` templating language method has all these variables in it - https://docs.djangoproject.com/en/5.2/ref/templates/builtins/#for
Variable | Description
-- | --
forloop.counter | The current iteration of the loop (1-indexed)
forloop.counter0 | The current iteration of the loop (0-indexed)
forloop.revcounter | The number of iterations from the end of the loop (1-indexed)
forloop.revcounter0 | The number of iterations from the end of the loop (0-indexed)
forloop.first | True if this is the first time through the loop
forloop.last | True if this is the last time through the …

Refactor: use Steps to dynamically generate steps list

---

tests/pytest/vital_records/tasks/test_email.py
web/vital_records/tasks/email.py
web/vital_records/templates/vital_records/email.html
web/vital_records/templates/vital_records/email.txt

Closes #292
In this PR, the email templates now use the request type from the vital records request object via the template's context instead of hard coded values. 
Note that this implementation will pass the string `Birth record` or `Marriage record` to the context since we are using [`request.get_type_display()`](https://docs.djangoproject.com/en/5.2/ref/models/instances/#django.db.models.Model.get_FOO_display). Also note that since #315 has been merged, the `type` field of `VitalRecordsRequest` is now populated so we can directly test this PR (at least for the `birth` type).
1. In your `.env` set `AZURE_COMMUNICATION_CONNECTION_STRING` and `DEFAULT_FROM_EMAIL` to blank
2. Run the `Django: Disaster Recovery` debugger and complete a `Replacement birth record` request
3. Run the `Django: …

Feat: email templates take record type in context

---

tests/pytest/vital_records/test_mixins.py
web/static/css/styles.css
web/vital_records/mixins.py
web/vital_records/templates/vital_records/_button_row.html
web/vital_records/templates/vital_records/request/confirm.html
web/vital_records/templates/vital_records/request/form.html
web/vital_records/templates/vital_records/request/order.html
web/vital_records/templates/vital_records/request/start.html
web/vital_records/templates/vital_records/request/statement.html
web/vital_records/templates/vital_records/request/type.html
web/vital_records/views/common.py
web/vital_records/views/marriage.py

closes #277 
- Creates an includes called Button Row that will add a Back/Next. The Next label is customizable.

Add Back button

---

tests/pytest/vital_records/tasks/test_email.py
web/vital_records/tasks/email.py

Closes #332
1. In your `.env` set `AZURE_COMMUNICATION_CONNECTION_STRING` and `DEFAULT_FROM_EMAIL` to blank
2. Run the `Django: Disaster Recovery` debugger and complete a `Replacement birth record` and `Replacement marriage record` request
3. Run the `Django: Qcluster` debugger to process the requests. This will generate a file named something like `date-id.log` in the `.inbox` folder for each request
4. Open each `.log` file and confirm that they show the string `Completed: Birth Record Request` for the birth request and `Completed: Marriage Record Request` for the marriage request in the subject line

Fix: email subject line to show record type

---

tests/pytest/vital_records/test_mixins.py
web/vital_records/mixins.py
web/vital_records/urls.py
web/vital_records/views/birth.py
web/vital_records/views/common.py
web/vital_records/views/marriage.py

As a part of adding the marriage flow, we introduced a path segment that represents the type of record.
For steps specific to the birth flow, the URL path will look like `/vital-records/request/birth/<id>/...`
For steps specific to the marriage flow, it will look like `/vital-records/request/marriage/<id>/...`
Before this PR, it was possible for the user to manually edit the URL and see the step for that type of flow rather than the one they actually picked.
For example,
- start the Birth record flow
- on the Name step, edit your URL to say `marriage` instead of `birth`
- see Marriage Name form in a Birth Records Request flow:
- filling out and submitting this Marriage Name form would save the `First Person` and `Second Person` names as the "Parent 1" and "Parent 2" names in the …

Feat: validate type in URL

---

terraform/alerts.tf

Closes #281
In this PR we exclude exceptions of type `ServiceResponseError` from the alert criteria so that we can reduce noise and focus on problems with our application rather than the monitoring service. We use the `has` string operator following the [documented best practices](https://learn.microsoft.com/en-us/kusto/query/best-practices?view=azure-data-explorer#in-short).
**Original query:**
**Updated query:**

Chore: clean up telemetry log search alerts

---

terraform/alerts.tf

Closes #377 
The Log Search alert rule query defined in Terraform actually runs in the Application Insights resource, and the column there is named "type", not "exceptionType".
The same exceptions data are [stored in two places in Azure](https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete#exception-telemetry):
- Application Insights resource (on the left nav bar, under `Monitoring` - `Logs`)
- Table: `exceptions`
- Columns: `problemId`, `type`, ...
- Log Analytics workspace resource (on the left nav bar, under `Logs`)
- Table: `AppExceptions`
- Columns: `ProblemId`, `ExceptionType`, ...
Log Search alert queries run against the Application Insights resource.

Fix: Log Search alert rule

---

web/vital_records/views/birth.py
web/vital_records/views/marriage.py

Closes #400 
Simple typo fix.
I took some time to look back at these notes I wrote in https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/pull/402#issuecomment-3313609299:
> Side note: I read more about `aria-describedby` / looked at the accessibility tree for our pages, and it looks like setting `aria-describedby` on `fieldset` doesn't actually do anything. In other words, the `form_hint` copy does not appear as a `description` on any object in the accessibility tree. This is a separate issue from what you're asking about. (But maybe it is relevant because if we remove our incorrect / non-functioning use of it, we don't have to worry about setting it?)
I'm not sure if I was looking in the wrong place in the accessibility tree or maybe it was actually this very bug …

Fix: form_hint_name

---

tests/pytest/vital_records/tasks/test_email.py
web/vital_records/tasks/email.py

Closes #388
This PR adds the `death` type to the `email` task so that it can support death certificate vital records requests. It also makes a small refactor to avoid duplicate calls to the `_format_record_type` function and adds a test for `_format_record_type` that was missing.
1. In your `.env` set `AZURE_COMMUNICATION_CONNECTION_STRING` and `DEFAULT_FROM_EMAIL` to blank
2. Run the `Django: Disaster Recovery` debugger and complete a `Replacement death record` request
3. Run the `Django: Qcluster` debugger to process the request. This will generate a file named something like `date-id.log` in the `.inbox` folder.
4. Open the `.log` file and confirm that it shows the string `Death` for the `Vital Record Type:` heading in both the text and html version of the email. Also confirm that …

Chore: add Death as a type for the email task

---

tests/pytest/vital_records/tasks/test_email.py
web/vital_records/tasks/email.py
web/vital_records/templates/vital_records/email.html
web/vital_records/templates/vital_records/email.txt

Closes #406 
This PR implements sending a confirmation email to the vital records requestor. We remove the line `(attached as a PDF to this email)` in the email templates so that the email to CDPH and to the requestor omits this. In addition, a helper `_create_base_email` is created to avoid some code duplication when creating more than one email. The emails to CDPH and to the requestor are created using this helper function. Finally, the return value of `EmailTask.handler` is turned into a tuple (where the first element corresponds to the result of sending the email to CDPH and the second element corresponds to the result of sending the email to the requestor) so that we can determine the result of the task in the admin as shown below:
1. In your `.env` set …

Feat: send confirmation email to requestor

---

web/vital_records/forms/common.py

Follow-up to #416 
After deploying `2025.09.2-rc1` to `test` we noticed this error:
```
Failed '<bound method PackageTask.handler of <web.vital_records.tasks.package.PackageTask object at 0x7171b4f10ec0>>' (package) - 'NoneType' object has no attribute 'astimezone' : Traceback (most recent call last):
File "/home/cdt/.local/lib/python3.12/site-packages/django_q/worker.py", line 103, in worker
res = f(*task["args"], **task["kwargs"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/cdt/.local/lib/python3.12/site-packages/web/vital_records/tasks/package.py", line 286, in handler
sworn_statement = SwornStatement.create_death_sworn_statement(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/cdt/.local/lib/python3.12/site-packages/web/vital_records/tasks/package.py", line …
```

Fix: ensure `started_at` is not null
