Office-of-Digital-Services/cdt-ods-disaster-recovery

README.md, pyproject.toml, web/__init__.py
Added some instructions in the README for getting started with the project locally.
=> Chore: project updates

README.md, appcontainer/Dockerfile
Forgot to update the package name from #5
=> Fix: docker build

appcontainer/Dockerfile, bin/reset_db.sh, manage.py, web/wsgi.py
Just messing around with the startup sequence while we're still in POC mode. Delete/recreate the database with each app restart, will load from fixtures from persistent storage.
=> Fix: docker startup

bin/start.sh, terraform/app_service.tf, terraform/environment.tf, terraform/output.tf
Getting the terraform to match the current state in preparation for building the other 2 environments, and turning on the infra pipeline in Azure DevOps.
=> Fix: terraform and app startup

.github/workflows/deploy.yml, terraform/azure-pipelines.yml
=> CI: Trigger Azure pipeline from GitHub Actions pipeline

.github/workflows/codeql.yml
Regenerated from GitHub: https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/settings/security_analysis
We don't even have any JavaScript right now.
Maybe this will fix this annoying merge blocking problem we're seeing on PRs:
=> CI: fix CodeQL workflow

terraform/container_app.tf, web/settings.py
=> Feat: init container app to reset DB

terraform/container_app.tf
=> Fix: DB connection settings in terraform

terraform/db.tf
You know, so a single login doesn't give access to the entire Internet!
=> Fix: enable sessions in `pgweb`

terraform/web.tf, web/core/urls.py, web/settings.py
To confirm email sending works in the hosting environment.
Part of #103
=> Feat: send a test email message

web/vital_records/templates/vital_records/request/confirm.html
`go back` should go to Step 1, not the eligibility page.
=> Fix: Confirm - Back button goes to step 1

web/static/css/styles.css, web/vital_records/templates/vital_records/request/confirm.html, web/vital_records/templates/vital_records/request/order.html, web/vital_records/templates/vital_records/submitted.html
=> Order form and Confirm page styling

web/vital_records/templates/vital_records/request/confirm.html
The name of the button was wrong in the copy.
=> Fix: Confirm page - Copy

terraform/.terraform.lock.hcl, terraform/db.tf, terraform/key_vault.tf, terraform/main.tf, terraform/web.tf, terraform/worker.tf
Replaces the `db` container app (unstable, doesn't persist data) with a true PostgreSQL server instance in Azure.
=> Refactor: PostgreSQL database server

.env.sample, compose.yml, terraform/db.tf, terraform/web.tf, terraform/worker.tf, tests/pytest/core/management/commands/test_ensure_db.py, web/core/management/commands/ensure_db.py, web/settings.py
* Setting for the `sslmode` parameter for connections to Postgres
* `=disable` for local development
* `=verify-full` for deployment to Azure
* Cleaning up environment and secrets
* Refactor and fix `ensure_db` command
=> Refactor: DB connection

terraform/db.tf, terraform/key_vault.tf, terraform/web.tf, terraform/worker.tf
When `access_policy` blocks are defined inline within the `azurerm_key_vault` resource, Terraform considers that resource authoritative for all access policies. 
If separate `azurerm_key_vault_access_policy` resources are defined, Terraform will try to reconcile these during the apply, often leading to the inline definition overwriting or deleting the standalone ones because it doesn't "know" about them in its own configuration block.
The solution is to centralize access policy management: Use only standalone `azurerm_key_vault_access_policy` resources to manage Key Vault access. Remove all inline access_policy blocks from the `azurerm_key_vault` resource.
Also, tell Key Vault to ignore policy changes (from its perspective): a lifecycle block in the `azurerm_key_vault` resource tells …
=> Fix: terraform Key Vault permissions

tests/pytest/core/management/commands/test_ensure_db.py, web/core/management/commands/ensure_db.py
Needed in environments where postgres_user is not a full SUPERUSER
the grant allows postgres_user to create a database on behalf of db_user
=> Fix: grant db_user to postgres_user

tests/pytest/core/management/commands/test_ensure_db.py, web/core/management/commands/ensure_db.py
So `db_user` can create tables in this schema, e.g. run migrations.
Part of #150
=> Fix: grant create for db_user on public schema

terraform/web.tf
So the superuser is created when the app initializes.
=> Fix: add superuser env vars

web/vital_records/migrations/0001_initial.py, web/vital_records/models.py
=> Add 3 other fires, alphabetize

web/settings.py
=> Fix: hardcode cert path from root

appcontainer/Dockerfile, web/settings.py
Follow-up to #225 #226 
Read from an environment variable that is created during the Docker build.
=> Fix: cert path from environment

web/settings.py
Using the new host names.
~On top of #243~
=> Fix: correct runtime environments

.github/workflows/deploy.yml, terraform/pipeline/tags.py
Ensure the Azure pipeline responds correctly to `test` and `prod` tags.
=> Fix: GH and Azure pipelines

web/vital_records/forms/marriage.py, web/vital_records/urls.py, web/vital_records/views/birth.py, web/vital_records/views/common.py, web/vital_records/views/marriage.py
=> Step 2 - Add County view

web/vital_records/forms/birth.py, web/vital_records/forms/common.py, web/vital_records/urls.py, web/vital_records/views/birth.py, web/vital_records/views/common.py, web/vital_records/views/marriage.py
Closes #288 
Built on top of #318 and #324
- Rename view to `DateOfEventView` and split off `DateOfBirthView` with birth-flow context
- Rename form to `DateOfEventForm`
- Create `DateOfMarriageView` with marriage-flow context
Both views can use the same form.
=> Step 3 (marriage flow) - Add Date view

tests/pytest/vital_records/tasks/test_package.py, web/vital_records/tasks/package.py
Follow-up to https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/pull/329
Addresses https://github.com/Office-of-Digital-Services/cdt-ods-disaster-recovery/pull/329#pullrequestreview-3161186741 by moving Application and Sworn Statement creation to their respective classes to improve encapsulation and maintainability.
=> Refactor: clean-up PDF Application creation logic

tests/pytest/vital_records/test_forms.py, web/vital_records/forms/common.py
Closes #360 
Built on top of #389
=> Feat: sworn statement relationships

tests/pytest/vital_records/death/test_views.py, web/vital_records/views/death.py
=> Feat: death flow - date of death
